dist: xenial
language: python
python:
  - "3.6"
addons:
  apt:
    packages:
      - python-dev
install:
  - pip install -r requirements.txt
script:
  - flake8 --max-line-length=99 testfm tests
  - make test-docstrings
